### ISSUE TITLE
Missing setup.py

### ISSUE THREAD

**Issue by wilderlopes** [Prograf-UFF/ConformalLayers#1]
Hi everybody,

Congrats on the paper! I am looking forward to reproducing it. However, I noticed the setup.py (used to install your library according to the documentation) is missing from the repo.
Is there any other we could install/run it?

**Comment by laffernandes** [comment]
Thank you, @wilderlopes. We have included the `setup.py` file.

Installing the required version of the Minkowski Engine may be tricky. Please, see the instructions at [How to Install ConformalLayers](https://github.com/Prograf-UFF/ConformalLayers#2-how-to-install-conformallayers) and let us know if you experience any problems.
