### ISSUE TITLE
Typo when importing progress_bar in Experiment 1

### ISSUE THREAD

**Issue by wilderlopes** [Prograf-UFF/ConformalLayers#2]
Upon trying to run Experiment I, the following error message appears. 

```bash
$ python BaseReSProNet.py --dataset=FashionMNIST
Traceback (most recent call last):
  File "BaseReSProNet.py", line 11, in <module>
    from Experiments.utils.utils import progress_bar
ModuleNotFoundError: No module named 'Experiments.utils.utils'
```

I believe it is a typo; according to the source code, it should be 

`from Experiments.utils.utils import progress_bar`

Environment:
- Running the Minkowski Engine Docker built with https://github.com/NVIDIA/MinkowskiEngine/blob/master/docker/Dockerfile 
- Ubuntu 20.04

**Comment by laffernandes** [comment]
Thank you @wilderlopes for pointing out this type. The `.py` scripts have been fixed.
