### ISSUE TITLE
how would you add bias?

### ISSUE THREAD

**Issue by alok** [Prograf-UFF/ConformalLayers#5]
the readme mentions you have a few ideas on how to do so, curious what they are. lack of bias seems to hurt performance, based on the conformallayers paper

**Comment by laffernandes** [comment]
Dear Alok, thank you for your interest in ConformalLayers. The current equations presented in the paper are not compatible with the use of bias. We are working on a new activation function that should support this operation in ConformalLayers. We will submit this work for publication and make the source code available once the research is complete.
